// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhrdOiJfKpVHpidU1UkzFyG7EyzRDdzx8',
    appId: '1:499392277869:web:ee77e123f57a1cc4dffe64',
    messagingSenderId: '499392277869',
    projectId: 'apprestaurant-f9ad9',
    authDomain: 'apprestaurant-f9ad9.firebaseapp.com',
    storageBucket: 'apprestaurant-f9ad9.firebasestorage.app',
    measurementId: 'G-QYVQL2ZSSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-NGtx_-4CxQA1h9BMnUNMU1S44zLG56g',
    appId: '1:499392277869:android:5949e811f0fdd08ddffe64',
    messagingSenderId: '499392277869',
    projectId: 'apprestaurant-f9ad9',
    storageBucket: 'apprestaurant-f9ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtGQDT4KlNZyhAnNdtafMa4p50S3H6MSQ',
    appId: '1:499392277869:ios:7a9fc3cd338c8935dffe64',
    messagingSenderId: '499392277869',
    projectId: 'apprestaurant-f9ad9',
    storageBucket: 'apprestaurant-f9ad9.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhrdOiJfKpVHpidU1UkzFyG7EyzRDdzx8',
    appId: '1:499392277869:web:3583506b124179f9dffe64',
    messagingSenderId: '499392277869',
    projectId: 'apprestaurant-f9ad9',
    authDomain: 'apprestaurant-f9ad9.firebaseapp.com',
    storageBucket: 'apprestaurant-f9ad9.firebasestorage.app',
    measurementId: 'G-69VX2V7W8E',
  );
}
